name: TerminalUnited Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Give gradlew permission
        run: chmod +x gradlew

      - name: Download Termux Bootstrap
        run: |
          mkdir -p app/src/main/cpp
          wget https://github.com/termux/termux-packages/releases/latest/download/bootstrap-aarch64.zip \
          -O app/src/main/cpp/bootstrap-aarch64.zip

      - name: Clean Project
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TerminalUnited-APK
          path: app/build/outputs/apk/release/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: TerminalUnited Build ${{ github.run_number }}
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}